name: ai-project
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - jupyter
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - pytorch
  - torchvision
  - pip
  - pip:
    - mlflow
    - wandb
